### PR TITLE
chore: bump go dependencies before release 0.82

### PR DESCRIPTION
**Pull request by slashpai**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note

```

### CODE REVIEW

**Comment by slashpai** [comment]
https://github.com/prometheus-operator/prometheus-operator/actions/runs/14484813130/job/40628393457?pr=7462

```
Error: ../../../go/pkg/mod/github.com/prometheus/prometheus@v0.303.0/util/logging/file.go:48:23: undefined: promslog.AllowedFormat
```
This looks to be from breaking change in https://github.com/prometheus/common/pull/754 
Since prometheus module v303.0 uses common version v0.62 just going to keep that same to avoid the conflict

File: test/framework/helpers.go [hunk 1]
```diff
@@ -261,7 +261,7 @@ func getMetricValue(b []byte, metricName string) (float64, error) {
 		}
 
 		seriesLabels := labels.Labels{}
-		parser.Metric(&seriesLabels)
+		parser.Labels(&seriesLabels)
```
Comment (slashpai) [inline test/framework/helpers.go:264]: https://github.com/prometheus-operator/prometheus-operator/actions/runs/14485091657/job/40629135389?pr=7462

```
  Error: test/e2e/alertmanager_test.go:49:16: could not import github.com/prometheus-operator/prometheus-operator/test/framework (-: # github.com/prometheus-operator/prometheus-operator/test/framework
  Error: test/framework/helpers.go:264:10: parser.Metric undefined (type textparse.Parser has no field or method Metric)) (typecheck)
  	testFramework "github.com/prometheus-operator/prometheus-operator/test/framework"
```

Breaking change due to https://github.com/prometheus/prometheus/commit/00b69efabb3cd3e213a2a34939f745d7156f7d47

**Review by simonpasquier — APPROVED** [review]
